name: CI (decommissioned)
on:
  - push
jobs:
  build:
    name: Build only on Node ${{ matrix.node }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node:
          - 18.x
        os:
          - ubuntu-latest
          - macOS-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Installation
        run: yarn install --frozen-lockfile
      - name: Skip tests and lint (decommissioned)
        run: echo "Project decommissioned — skipping tests and linting."
      - name: Build
        run: yarn build
